# Generated by Django 5.0.3 on 2024-03-31 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('our', '0002_alter_book_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='year',
        ),
    ]
