# Generated by Django 5.0.3 on 2024-04-01 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our', '0003_remove_book_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tur',
            new_name='Category',
        ),
        migrations.AddField(
            model_name='book',
            name='bolim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='our.category'),
        ),
    ]
